/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        ivory: {
          DEFAULT: 'var(--ivory)',
          2: 'var(--ivory-2)',
          3: 'var(--ivory-3)',
        },
        linen: 'var(--linen)',
        charcoal: {
          DEFAULT: 'var(--charcoal)',
          2: 'var(--charcoal-2)',
        },
        ink: {
          DEFAULT: 'var(--ink)',
          soft: 'var(--ink-soft)',
          mute: 'var(--ink-mute)',
          // legacy admin scale preserved
          50: 'var(--ink-50)',
          100: 'var(--ink-100)',
          200: 'var(--ink-200)',
          300: 'var(--ink-300)',
          400: 'var(--ink-400)',
          500: 'var(--ink-500)',
          600: 'var(--ink-600)',
          700: 'var(--ink-700)',
          800: 'var(--ink-800)',
          900: 'var(--ink-900)',
        },
        champagne: 'var(--champagne)',
        gold: {
          DEFAULT: 'var(--gold)',
          deep: 'var(--gold-deep)',
          light: 'var(--gold-light)',
          pale: 'var(--gold-pale)',
          // legacy aliases used by admin
          dark: 'var(--gold-dark)',
          champagne: 'var(--gold-champagne)',
        },
        line: {
          DEFAULT: 'var(--line)',
          soft: 'var(--line-soft)',
        },
        // legacy tokens preserved for admin
        bg: {
          DEFAULT: 'var(--bg)',
          deep: 'var(--bg-deep)',
          card: 'var(--bg-card)',
          soft: 'var(--bg-soft)',
        },
        'black-deep': 'var(--bg-deep)',
        'black-soft': 'var(--bg-soft)',
        'black-card': 'var(--bg-card)',
        danger: 'var(--danger)',
        success: 'var(--success)',
      },
      fontFamily: {
        display: ['var(--font-display)', 'Georgia', 'serif'],
        serif: ['var(--font-display)', 'Georgia', 'serif'],
        body: ['var(--font-body)', 'system-ui', 'sans-serif'],
        sans: ['var(--font-body)', 'system-ui', 'sans-serif'],
      },
      letterSpacing: {
        'ultra': '0.4em',
        'wide-sm': '0.08em',
        'luxe': '0.25em',
        'luxe-wide': '0.35em',
      },
      maxWidth: {
        '8xl': '88rem',
        '10xl': '104rem',
      },
      borderRadius: {
        luxe: '14px',
        'luxe-lg': '20px',
        'luxe-xl': '28px',
        'kx': '2px',
      },
      boxShadow: {
        'gold-soft': '0 16px 50px -20px rgba(184,155,94,0.35)',
        'gold-glow': '0 0 40px -8px rgba(184,155,94,0.45)',
        'card-luxe': '0 24px 70px -32px rgba(28,26,23,0.18)',
        'card-hover': '0 32px 90px -32px rgba(28,26,23,0.28)',
        'soft': '0 4px 24px -8px rgba(28,26,23,0.10)',
        'elevate': '0 12px 40px -16px rgba(28,26,23,0.22)',
        'luxe': '0 30px 70px rgba(28,26,23,0.14)',
        'kx': '0 8px 30px rgba(28,26,23,0.08)',
        'kx-hover': '0 24px 60px rgba(28,26,23,0.16)',
      },
      transitionTimingFunction: {
        'luxe': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'editorial': 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease forwards',
        'fade-up': 'fadeUp 0.7s ease forwards',
        'scale-in': 'scaleIn 0.5s ease forwards',
        'shimmer': 'shimmer 2.5s linear infinite',
        'glow': 'glow 3s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 9s ease-in-out infinite',
        'spin-slow': 'spin 8s linear infinite',
        'reveal': 'reveal 1s cubic-bezier(0.16,1,0.3,1) forwards',
        'draw-line': 'drawLine 1.2s ease forwards',
        'pulse-gold': 'pulseGold 2.5s ease-in-out infinite',
        'slide-down': 'slideDown 0.4s cubic-bezier(0.16,1,0.3,1) forwards',
        'splash-out': 'splashOut 0.8s cubic-bezier(0.7,0,0.84,0) forwards',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeUp: { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.96)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        glow: { '0%,100%': { boxShadow: '0 0 20px rgba(184,155,94,0.15)' }, '50%': { boxShadow: '0 0 40px rgba(184,155,94,0.35)' } },
        float: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        reveal: { '0%': { opacity: '0', transform: 'translateY(40px) scale(0.98)' }, '100%': { opacity: '1', transform: 'translateY(0) scale(1)' } },
        drawLine: { '0%': { transform: 'scaleX(0)' }, '100%': { transform: 'scaleX(1)' } },
        pulseGold: { '0%,100%': { opacity: '0.6' }, '50%': { opacity: '1' } },
        slideDown: { '0%': { opacity: '0', transform: 'translateY(-12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        splashOut: { '0%': { opacity: '1', transform: 'scale(1)' }, '100%': { opacity: '0', transform: 'scale(1.1)' } },
      },
    },
  },
  plugins: [],
};
